version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "chore"
      - "github_actions"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/travel-assistant/app"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "chore"
      - "python"
    groups:
      python-dependencies:
        patterns:
          - "*"
